<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOedpdon\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOedpdon/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOedpdon.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOedpdon\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOedpdon\appProdProjectContainer([
    'container.build_hash' => 'Oedpdon',
    'container.build_id' => '08dda5f8',
    'container.build_time' => 1588449059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOedpdon');
